### PR TITLE
Update and tidy all modules

### PR DESCRIPTION
**Pull request by jhesketh**

### CODE REVIEW

**Review by zerok — APPROVED** [review]

**Comment by iainlane** [comment]
I just merged a bunch of dependabot PRs before seeing this - looks like this might all have been taken care of by those, care to take a second look please? Thanks!

**Comment by jhesketh** [comment]
> I just merged a bunch of dependabot PRs before seeing this - looks like this might all have been taken care of by those, care to take a second look please? Thanks!

Yep, I think it was taken care of, so I've just changed this to update the remaining modules.

**Review by iainlane — APPROVED** [review]
:+1:

**Comment by jhesketh** [comment]
I think an owner needs to kick the build along/merge please

**Comment by zerok** [comment]
Done, thank you 🙂

**Pull request merged**
